export const fakeRecipes = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 11,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 8,
    spoonacularScore: 72.0,
    healthScore: 25.0,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 287.28,
    extendedIngredients: [
      {
        id: 1123,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'egg.png',
        consistency: 'solid',
        name: 'egg',
        nameClean: 'egg',
        original: '1 large egg',
        originalString: '1 large egg',
        originalName: 'egg',
        amount: 1.0,
        unit: 'large',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
          metric: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
        },
      },
      {
        id: 1077,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'milk.png',
        consistency: 'liquid',
        name: 'milk',
        nameClean: 'milk',
        original: '1 tbsp milk',
        originalString: '1 tbsp milk',
        originalName: 'milk',
        amount: 1.0,
        unit: 'tbsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
          metric: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
        },
      },
      {
        id: 35137,
        aisle: 'Ethnic Foods;Baking',
        image: 'cornmeal.png',
        consistency: 'solid',
        name: 'yellow cornmeal',
        nameClean: 'cornmeal',
        original: '1/3 cup yellow cornmeal',
        originalString: '1/3 cup yellow cornmeal',
        originalName: 'yellow cornmeal',
        amount: 0.3333333333333333,
        unit: 'cup',
        meta: ['yellow'],
        metaInformation: ['yellow'],
        measures: {
          us: {
            amount: 0.333,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 78.863,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 2009,
        aisle: 'Spices and Seasonings',
        image: 'chili-powder.jpg',
        consistency: 'solid',
        name: 'chile powder',
        nameClean: 'chili powder',
        original: '1 tsp chile powder',
        originalString: '1 tsp chile powder',
        originalName: 'chile powder',
        amount: 1.0,
        unit: 'tsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
          metric: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
        },
      },
      {
        id: 2031,
        aisle: 'Spices and Seasonings',
        image: 'chili-powder.jpg',
        consistency: 'solid',
        name: 'cayenne',
        nameClean: 'ground cayenne pepper',
        original: '1/2 tsp cayenne powder',
        originalString: '1/2 tsp cayenne powder',
        originalName: 'cayenne powder',
        amount: 0.5,
        unit: 'tsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 1012028,
        aisle: 'Spices and Seasonings',
        image: 'paprika.jpg',
        consistency: 'solid',
        name: 'smoked paprika',
        nameClean: 'smoked paprika',
        original: '1/2 tsp hot smoked paprika',
        originalString: '1/2 tsp hot smoked paprika',
        originalName: 'hot smoked paprika',
        amount: 0.5,
        unit: 'tsp',
        meta: ['smoked', 'hot'],
        metaInformation: ['smoked', 'hot'],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 1002020,
        aisle: 'Spices and Seasonings',
        image: 'granulated-garlic.png',
        consistency: 'solid',
        name: 'granulated garlic',
        nameClean: 'granulated garlic',
        original: '1/2 tsp granulated garlic',
        originalString: '1/2 tsp granulated garlic',
        originalName: 'granulated garlic',
        amount: 0.5,
        unit: 'tsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 15010,
        aisle: 'Seafood',
        image: 'catfish.jpg',
        consistency: 'solid',
        name: 'catfish filets',
        nameClean: 'catfish',
        original: '4 5-oz. skinless catfish filets',
        originalString: '4 5-oz. skinless catfish filets',
        originalName: 'skinless catfish filets',
        amount: 20.0,
        unit: 'oz',
        meta: ['skinless'],
        metaInformation: ['skinless'],
        measures: {
          us: {
            amount: 20.0,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 566.99,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 4053,
        aisle: 'Oil, Vinegar, Salad Dressing',
        image: 'olive-oil.jpg',
        consistency: 'liquid',
        name: 'olive oil',
        nameClean: 'olive oil',
        original: '3 tbsp olive oil',
        originalString: '3 tbsp olive oil',
        originalName: 'olive oil',
        amount: 3.0,
        unit: 'tbsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
          metric: {
            amount: 3.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
        },
      },
      {
        id: 1012047,
        aisle: 'Spices and Seasonings',
        image: 'salt.jpg',
        consistency: 'solid',
        name: 'sea salt',
        nameClean: 'coarse sea salt',
        original: 'sea salt',
        originalString: 'sea salt',
        originalName: 'sea salt',
        amount: 1.0,
        unit: 'serving',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'serving',
            unitLong: 'serving',
          },
          metric: {
            amount: 1.0,
            unitShort: 'serving',
            unitLong: 'serving',
          },
        },
      },
      {
        id: 10211821,
        aisle: 'Produce',
        image: 'bell-pepper-orange.png',
        consistency: 'solid',
        name: 'bell pepper',
        nameClean: 'bell pepper',
        original: 'freshly ground black pepper',
        originalString: 'freshly ground black pepper',
        originalName: 'freshly ground black pepper',
        amount: 1.0,
        unit: 'serving',
        meta: ['black', 'freshly ground'],
        metaInformation: ['black', 'freshly ground'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'serving',
            unitLong: 'serving',
          },
          metric: {
            amount: 1.0,
            unitShort: 'serving',
            unitLong: 'serving',
          },
        },
      },
      {
        id: 4641,
        aisle: 'Condiments',
        image: 'mayonnaise.png',
        consistency: 'liquid',
        name: 'light mayonnaise',
        nameClean: 'light mayonnaise',
        original: '3/4 cup light mayonnaise',
        originalString: '3/4 cup light mayonnaise',
        originalName: 'light mayonnaise',
        amount: 0.75,
        unit: 'cup',
        meta: ['light'],
        metaInformation: ['light'],
        measures: {
          us: {
            amount: 0.75,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 177.441,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 10011937,
        aisle: 'Canned and Jarred',
        image: 'dill-pickles.jpg',
        consistency: 'solid',
        name: 'dill pickle',
        nameClean: 'dill pickles',
        original: '2 tbsp finely chopped dill pickle',
        originalString: '2 tbsp finely chopped dill pickle',
        originalName: 'finely chopped dill pickle',
        amount: 2.0,
        unit: 'tbsp',
        meta: ['finely chopped'],
        metaInformation: ['finely chopped'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
          metric: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
        },
      },
      {
        id: 11979,
        aisle: 'Canned and Jarred;Produce;Ethnic Foods',
        image: 'jalapeno-pepper.png',
        consistency: 'solid',
        name: 'jalapeno chile',
        nameClean: 'jalapeno pepper',
        original: '1 tbsp finely chopped jalapeno chile',
        originalString: '1 tbsp finely chopped jalapeno chile',
        originalName: 'finely chopped jalapeno chile',
        amount: 1.0,
        unit: 'tbsp',
        meta: ['finely chopped'],
        metaInformation: ['finely chopped'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
          metric: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
        },
      },
      {
        id: 11291,
        aisle: 'Produce',
        image: 'spring-onions.jpg',
        consistency: 'solid',
        name: 'scallion',
        nameClean: 'spring onions',
        original: '1 tbsp finely chopped scallion (white and green parts)',
        originalString: '1 tbsp finely chopped scallion (white and green parts)',
        originalName: 'finely chopped scallion (white and green parts)',
        amount: 1.0,
        unit: 'tbsp',
        meta: ['white', 'green', 'finely chopped', '( and parts)'],
        metaInformation: ['white', 'green', 'finely chopped', '( and parts)'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
          metric: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
        },
      },
      {
        id: 93640,
        aisle: 'Canned and Jarred',
        image: 'pickle-juice.jpg',
        consistency: 'solid',
        name: 'dill pickle juice',
        nameClean: 'pickle juice',
        original: '1 tsp dill pickle juice',
        originalString: '1 tsp dill pickle juice',
        originalName: 'dill pickle juice',
        amount: 1.0,
        unit: 'tsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
          metric: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
        },
      },
      {
        id: 9152,
        aisle: 'Produce',
        image: 'lemon-juice.jpg',
        consistency: 'liquid',
        name: 'lemon juice',
        nameClean: 'lemon juice',
        original: '1 tsp fresh lemon juice',
        originalString: '1 tsp fresh lemon juice',
        originalName: 'fresh lemon juice',
        amount: 1.0,
        unit: 'tsp',
        meta: ['fresh'],
        metaInformation: ['fresh'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
          metric: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
        },
      },
    ],
    id: 640166,
    title: 'Cornmeal-Crusted Catfish with Cajun Seasoning and Spicy Tartar Sauce',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      'https://www.foodista.com/recipe/XGXZYJ88/cornmeal-crusted-catfish-with-cajun-seasoning-and-spicy-tartar-sauce',
    image: 'https://spoonacular.com/recipeImages/640166-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Cornmeal-Crusted Catfish with Cajun Seasoning and Spicy Tartar Sauce is a main course that serves 4. One portion of this dish contains roughly <b>27g of protein</b>, <b>26g of fat</b>, and a total of <b>420 calories</b>. For <b>$2.87 per serving</b>, this recipe <b>covers 26%</b> of your daily requirements of vitamins and minerals. Not a lot of people made this recipe, and 8 would say it hit the spot. This recipe is typical of Cajun cuisine. From preparation to the plate, this recipe takes around <b>around 45 minutes</b>. If you have granulated garlic, dill pickle juice, scallion, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. It is a good option if you\'re following a <b>gluten free and pescatarian</b> diet. Taking all factors into account, this recipe <b>earns a spoonacular score of 71%</b>, which is solid. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/spicy-catfish-tenders-with-cajun-tartar-sauce-86027">Spicy Catfish Tenders With Cajun Tartar Sauce</a>, <a href="https://spoonacular.com/recipes/spicy-cornmeal-crusted-catfish-86038">Spicy Cornmeal-crusted Catfish</a>, and <a href="https://spoonacular.com/recipes/spicy-cornmeal-crusted-catfish-86033">Spicy Cornmeal-Crusted Catfish</a>.',
    cuisines: ['Cajun', 'Creole'],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['gluten free', 'pescatarian'],
    occasions: [],
    instructions:
      'Whisk the egg and milk in a medium bowl. Combine the cornmeal, chile powder, cayenne powder, paprika, and garlic in a large zip-top bag.\nDip each catfish filet in the egg mixture. Let excess egg drip off and place the filets in the bag with the cornmeal mixture. Zip the top and shake the bag until all pieces are well coated.\nRemove the filets and lay side by side on a plate (do not overlap). Place in the refrigerator for 30 minutes. (Refrigeration helps keep the crust adhered during cooking.)\nWhile the fish chills, make the sauce. Whisk the first 6 ingredients (through lemon juice) in a small bowl. Season with salt and pepper and set aside.\nHeat a large, nonstick skillet over medium heat and add the olive oil. When the oil is hot (but not smoking), season the catfish filets with salt and pepper and add to the skillet. Fry until crispy on the outside and tender on the inside, 3-4 minutes per side, depending on thickness.\nDivide the fish among 4 plates and top each with a dollop of tartar sauce or pass the sauce at the table.',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'Whisk the egg and milk in a medium bowl.',
            ingredients: [
              {
                id: 1077,
                name: 'milk',
                localizedName: 'milk',
                image: 'milk.png',
              },
              {
                id: 1123,
                name: 'egg',
                localizedName: 'egg',
                image: 'egg.png',
              },
            ],
            equipment: [
              {
                id: 404661,
                name: 'whisk',
                localizedName: 'whisk',
                image: 'whisk.png',
              },
              {
                id: 404783,
                name: 'bowl',
                localizedName: 'bowl',
                image: 'bowl.jpg',
              },
            ],
          },
          {
            number: 2,
            step: 'Combine the cornmeal, chile powder, cayenne powder, paprika, and garlic in a large zip-top bag.',
            ingredients: [
              {
                id: 2009,
                name: 'chili powder',
                localizedName: 'chili powder',
                image: 'chili-powder.jpg',
              },
              {
                id: 35137,
                name: 'cornmeal',
                localizedName: 'cornmeal',
                image: 'cornmeal.png',
              },
              {
                id: 2031,
                name: 'ground cayenne pepper',
                localizedName: 'ground cayenne pepper',
                image: 'chili-powder.jpg',
              },
              {
                id: 2028,
                name: 'paprika',
                localizedName: 'paprika',
                image: 'paprika.jpg',
              },
              {
                id: 11215,
                name: 'garlic',
                localizedName: 'garlic',
                image: 'garlic.png',
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: 'Dip each catfish filet in the egg mixture.',
            ingredients: [
              {
                id: 15010,
                name: 'catfish fillets',
                localizedName: 'catfish fillets',
                image: 'catfish.jpg',
              },
              {
                id: 0,
                name: 'dip',
                localizedName: 'dip',
                image: '',
              },
              {
                id: 1123,
                name: 'egg',
                localizedName: 'egg',
                image: 'egg.png',
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: 'Let excess egg drip off and place the filets in the bag with the cornmeal mixture. Zip the top and shake the bag until all pieces are well coated.',
            ingredients: [
              {
                id: 35137,
                name: 'cornmeal',
                localizedName: 'cornmeal',
                image: 'cornmeal.png',
              },
              {
                id: 0,
                name: 'shake',
                localizedName: 'shake',
                image: '',
              },
              {
                id: 1123,
                name: 'egg',
                localizedName: 'egg',
                image: 'egg.png',
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: 'Remove the filets and lay side by side on a plate (do not overlap).',
            ingredients: [],
            equipment: [],
          },
          {
            number: 6,
            step: 'Place in the refrigerator for 30 minutes. (Refrigeration helps keep the crust adhered during cooking.)',
            ingredients: [
              {
                id: 0,
                name: 'crust',
                localizedName: 'crust',
                image: '',
              },
            ],
            equipment: [],
            length: {
              number: 30,
              unit: 'minutes',
            },
          },
          {
            number: 7,
            step: 'While the fish chills, make the sauce.',
            ingredients: [
              {
                id: 0,
                name: 'sauce',
                localizedName: 'sauce',
                image: '',
              },
              {
                id: 10115261,
                name: 'fish',
                localizedName: 'fish',
                image: 'fish-fillet.jpg',
              },
            ],
            equipment: [],
          },
          {
            number: 8,
            step: 'Whisk the first 6 ingredients (through lemon juice) in a small bowl. Season with salt and pepper and set aside.',
            ingredients: [
              {
                id: 1102047,
                name: 'salt and pepper',
                localizedName: 'salt and pepper',
                image: 'salt-and-pepper.jpg',
              },
              {
                id: 9152,
                name: 'lemon juice',
                localizedName: 'lemon juice',
                image: 'lemon-juice.jpg',
              },
            ],
            equipment: [
              {
                id: 404661,
                name: 'whisk',
                localizedName: 'whisk',
                image: 'whisk.png',
              },
              {
                id: 404783,
                name: 'bowl',
                localizedName: 'bowl',
                image: 'bowl.jpg',
              },
            ],
          },
          {
            number: 9,
            step: 'Heat a large, nonstick skillet over medium heat and add the olive oil. When the oil is hot (but not smoking), season the catfish filets with salt and pepper and add to the skillet. Fry until crispy on the outside and tender on the inside, 3-4 minutes per side, depending on thickness.',
            ingredients: [
              {
                id: 1102047,
                name: 'salt and pepper',
                localizedName: 'salt and pepper',
                image: 'salt-and-pepper.jpg',
              },
              {
                id: 15010,
                name: 'catfish fillets',
                localizedName: 'catfish fillets',
                image: 'catfish.jpg',
              },
              {
                id: 4053,
                name: 'olive oil',
                localizedName: 'olive oil',
                image: 'olive-oil.jpg',
              },
              {
                id: 4582,
                name: 'cooking oil',
                localizedName: 'cooking oil',
                image: 'vegetable-oil.jpg',
              },
            ],
            equipment: [
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
            length: {
              number: 4,
              unit: 'minutes',
            },
          },
          {
            number: 10,
            step: 'Divide the fish among 4 plates and top each with a dollop of tartar sauce or pass the sauce at the table.',
            ingredients: [
              {
                id: 27049,
                name: 'tartar sauce',
                localizedName: 'tartar sauce',
                image: 'sour-cream.jpg',
              },
              {
                id: 0,
                name: 'sauce',
                localizedName: 'sauce',
                image: '',
              },
              {
                id: 10115261,
                name: 'fish',
                localizedName: 'fish',
                image: 'fish-fillet.jpg',
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      'https://spoonacular.com/cornmeal-crusted-catfish-with-cajun-seasoning-and-spicy-tartar-sauce-640166',
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 15,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 26,
    spoonacularScore: 32.0,
    healthScore: 2.0,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 66.8,
    extendedIngredients: [
      {
        id: 10019903,
        aisle: 'Baking',
        image: 'chocolate-chips.jpg',
        consistency: 'solid',
        name: 'semi sweet chocolate chips',
        nameClean: 'semisweet chocolate chips',
        original: '2 c. (12 oz. pkg.) semi-sweet chocolate chips',
        originalString: '2 c. (12 oz. pkg.) semi-sweet chocolate chips',
        originalName: '(12 oz. pkg.) semi-sweet chocolate chips',
        amount: 2.0,
        unit: 'c',
        meta: ['(12 oz. pkg.)'],
        metaInformation: ['(12 oz. pkg.)'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 473.176,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 1095,
        aisle: 'Baking',
        image: 'evaporated-milk.png',
        consistency: 'solid',
        name: 'sweetened condensed milk',
        nameClean: 'sweetened condensed milk',
        original: '14 oz. can sweetened condensed milk',
        originalString: '14 oz. can sweetened condensed milk',
        originalName: 'sweetened condensed milk',
        amount: 14.0,
        unit: 'oz',
        meta: ['sweetened', 'canned'],
        metaInformation: ['sweetened', 'canned'],
        measures: {
          us: {
            amount: 14.0,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 396.893,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 2050,
        aisle: 'Baking',
        image: 'vanilla-extract.jpg',
        consistency: 'liquid',
        name: 'vanilla extract',
        nameClean: 'vanilla extract',
        original: '1 t. vanilla extract',
        originalString: '1 t. vanilla extract',
        originalName: 'vanilla extract',
        amount: 1.0,
        unit: 't',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
          metric: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
        },
      },
      {
        id: 2047,
        aisle: 'Spices and Seasonings',
        image: 'salt.jpg',
        consistency: 'solid',
        name: 'salt',
        nameClean: 'salt',
        original: '1/8 t. salt',
        originalString: '1/8 t. salt',
        originalName: 'salt',
        amount: 0.125,
        unit: 't',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 0.125,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.125,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 10119116,
        aisle: 'Baking',
        image: 'marshmallows-mini.png',
        consistency: 'solid',
        name: 'mini marshmallows',
        nameClean: 'mini marshmallows',
        original: '3 c. mini-marshmallows',
        originalString: '3 c. mini-marshmallows',
        originalName: 'mini-marshmallows',
        amount: 3.0,
        unit: 'c',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 709.764,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 12155,
        aisle: 'Nuts;Baking',
        image: 'walnuts.jpg',
        consistency: 'solid',
        name: 'walnuts',
        nameClean: 'walnuts',
        original: '1 1/2 c. toasted, chopped walnuts',
        originalString: '1 1/2 c. toasted, chopped walnuts',
        originalName: 'toasted, chopped walnuts',
        amount: 1.5,
        unit: 'c',
        meta: ['toasted', 'chopped'],
        metaInformation: ['toasted', 'chopped'],
        measures: {
          us: {
            amount: 1.5,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 354.882,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
    ],
    id: 631882,
    title: '5-Minute Rocky Road Fudge',
    readyInMinutes: 45,
    servings: 15,
    sourceUrl: 'https://www.foodista.com/recipe/HYGDSRK2/5-minute-rocky-road-fudge',
    image: 'https://spoonacular.com/recipeImages/631882-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Forget going out to eat or ordering takeout every time you crave Cajun food. Try making 5-Minute Rocky Road Fudge at home. One serving contains <b>333 calories</b>, <b>6g of protein</b>, and <b>19g of fat</b>. This gluten free recipe serves 15 and costs <b>67 cents per serving</b>. It is brought to you by Foodista. 26 people were impressed by this recipe. If you have walnuts, condensed milk, mini-marshmallows, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes approximately <b>approximately 45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 30%</b>, which is rather bad. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/10-minute-rocky-road-fudge-591197">10 Minute Rocky Road Fudge</a>, <a href="https://spoonacular.com/recipes/rocky-road-fudge-517390">Rocky Road Fudge</a>, and <a href="https://spoonacular.com/recipes/rocky-road-fudge-1060986">Rocky Road Fudge</a>.',
    cuisines: ['Cajun', 'Creole'],
    dishTypes: [],
    diets: ['gluten free'],
    occasions: [],
    instructions:
      'Line a 13x9-inch pan with foil, lightly spray with cooking spray. Set aside.\nIn a large, microwave safe bowl, add chocolate chips and condensed milk. Microwave for about 40 seconds, or until the chips are just melted when you stir them. If needed, continue to microwave in 15 second increments until melted. Do not overcook. Immediately stir in vanilla and salt. Then fold in the marshmallows and nuts.\nWorking quickly, spread and press fudge into the prepared pan. Refrigerate until completely cooled before cutting into squares.',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'Line a 13x9-inch pan with foil, lightly spray with cooking spray. Set aside.',
            ingredients: [
              {
                id: 4679,
                name: 'cooking spray',
                localizedName: 'cooking spray',
                image: 'cooking-spray.png',
              },
            ],
            equipment: [
              {
                id: 404765,
                name: 'aluminum foil',
                localizedName: 'aluminum foil',
                image: 'aluminum-foil.png',
              },
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
          },
          {
            number: 2,
            step: 'In a large, microwave safe bowl, add chocolate chips and condensed milk. Microwave for about 40 seconds, or until the chips are just melted when you stir them. If needed, continue to microwave in 15 second increments until melted. Do not overcook. Immediately stir in vanilla and salt. Then fold in the marshmallows and nuts.',
            ingredients: [
              {
                id: 99278,
                name: 'chocolate chips',
                localizedName: 'chocolate chips',
                image: 'chocolate-chips.jpg',
              },
              {
                id: 1095,
                name: 'sweetened condensed milk',
                localizedName: 'sweetened condensed milk',
                image: 'evaporated-milk.png',
              },
              {
                id: 19116,
                name: 'marshmallows',
                localizedName: 'marshmallows',
                image: 'normal-marshmallows.jpg',
              },
              {
                id: 1052050,
                name: 'vanilla',
                localizedName: 'vanilla',
                image: 'vanilla.jpg',
              },
              {
                id: 11408,
                name: 'french fries',
                localizedName: 'french fries',
                image: 'french-fries-isolated.jpg',
              },
              {
                id: 12135,
                name: 'nuts',
                localizedName: 'nuts',
                image: 'nuts-mixed.jpg',
              },
              {
                id: 2047,
                name: 'salt',
                localizedName: 'salt',
                image: 'salt.jpg',
              },
            ],
            equipment: [
              {
                id: 404762,
                name: 'microwave',
                localizedName: 'microwave',
                image: 'microwave.jpg',
              },
              {
                id: 404783,
                name: 'bowl',
                localizedName: 'bowl',
                image: 'bowl.jpg',
              },
            ],
          },
          {
            number: 3,
            step: 'Working quickly, spread and press fudge into the prepared pan. Refrigerate until completely cooled before cutting into squares.',
            ingredients: [
              {
                id: 0,
                name: 'spread',
                localizedName: 'spread',
                image: '',
              },
              {
                id: 19100,
                name: 'fudge',
                localizedName: 'fudge',
                image: 'fudge-isolated.jpg',
              },
            ],
            equipment: [
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl: 'https://spoonacular.com/5-minute-rocky-road-fudge-631882',
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 13,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 53,
    spoonacularScore: 99.0,
    healthScore: 100.0,
    creditsText: "Lisa's Vegetarian Kitchen",
    license: 'CC BY 2.5 CA',
    sourceName: 'Food and Spice',
    pricePerServing: 185.77,
    extendedIngredients: [
      {
        id: 20040,
        aisle: 'Pasta and Rice',
        image: 'uncooked-brown-rice.png',
        consistency: 'solid',
        name: 'brown rice',
        nameClean: 'brown rice',
        original: '2/3 cup dried brown rice (2 cups cooked)',
        originalString: '2/3 cup dried brown rice (2 cups cooked)',
        originalName: '2/3 cup dried brown rice cooked)',
        amount: 2.0,
        unit: 'cups',
        meta: ['dried', 'cooked'],
        metaInformation: ['dried', 'cooked'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 473.176,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'solid',
        name: 'carrots',
        nameClean: 'carrot',
        original: '2 medium carrots, sliced',
        originalString: '2 medium carrots, sliced',
        originalName: 'carrots, sliced',
        amount: 2.0,
        unit: 'medium',
        meta: ['sliced'],
        metaInformation: ['sliced'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 2.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
      {
        id: 11143,
        aisle: 'Produce',
        image: 'celery.jpg',
        consistency: 'solid',
        name: 'celery',
        nameClean: 'celery',
        original: '2 stalks celery, sliced',
        originalString: '2 stalks celery, sliced',
        originalName: 'celery, sliced',
        amount: 2.0,
        unit: 'stalks',
        meta: ['sliced'],
        metaInformation: ['sliced'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'stalks',
            unitLong: 'stalks',
          },
          metric: {
            amount: 2.0,
            unitShort: 'stalks',
            unitLong: 'stalks',
          },
        },
      },
      {
        id: 2007,
        aisle: 'Spices and Seasonings',
        image: 'celery-seed.jpg',
        consistency: 'solid',
        name: 'celery seed',
        nameClean: 'celery seed',
        original: '1 teaspoon celery seed',
        originalString: '1 teaspoon celery seed',
        originalName: 'celery seed',
        amount: 1.0,
        unit: 'teaspoon',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
          metric: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
        },
      },
      {
        id: 16032,
        aisle: 'Pasta and Rice;Canned and Jarred',
        image: 'kidney-beans.jpg',
        consistency: 'solid',
        name: 'dried kidney beans',
        nameClean: 'dried kidney beans',
        original: '2/3 cup dried kidney beans (2 cups cooked)',
        originalString: '2/3 cup dried kidney beans (2 cups cooked)',
        originalName: '2/3 cup dried kidney beans cooked)',
        amount: 2.0,
        unit: 'cups',
        meta: ['dried', 'cooked'],
        metaInformation: ['dried', 'cooked'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 473.176,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 2023,
        aisle: 'Produce;Spices and Seasonings',
        image: 'marjoram.jpg',
        consistency: 'solid',
        name: 'dried marjoram',
        nameClean: 'marjoram',
        original: '1 teaspoon dried marjoram',
        originalString: '1 teaspoon dried marjoram',
        originalName: 'dried marjoram',
        amount: 1.0,
        unit: 'teaspoon',
        meta: ['dried'],
        metaInformation: ['dried'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
          metric: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
        },
      },
      {
        id: 2042,
        aisle: 'Spices and Seasonings',
        image: 'thyme.jpg',
        consistency: 'solid',
        name: 'dried thyme',
        nameClean: 'dried thyme',
        original: '2 teaspoons dried thyme',
        originalString: '2 teaspoons dried thyme',
        originalName: 'dried thyme',
        amount: 2.0,
        unit: 'teaspoons',
        meta: ['dried'],
        metaInformation: ['dried'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 2.0,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 11209,
        aisle: 'Produce',
        image: 'eggplant.png',
        consistency: 'solid',
        name: 'eggplant',
        nameClean: 'eggplant',
        original: '1 medium eggplant, chopped',
        originalString: '1 medium eggplant, chopped',
        originalName: 'eggplant, chopped',
        amount: 1.0,
        unit: 'medium',
        meta: ['chopped'],
        metaInformation: ['chopped'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'medium',
            unitLong: 'medium',
          },
          metric: {
            amount: 1.0,
            unitShort: 'medium',
            unitLong: 'medium',
          },
        },
      },
      {
        id: 11215,
        aisle: 'Produce',
        image: 'garlic.png',
        consistency: 'solid',
        name: 'garlic',
        nameClean: 'garlic',
        original: '2 cloves garlic, minced or crushed',
        originalString: '2 cloves garlic, minced or crushed',
        originalName: 'garlic, minced or crushed',
        amount: 2.0,
        unit: 'cloves',
        meta: ['minced', 'crushed'],
        metaInformation: ['minced', 'crushed'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'cloves',
            unitLong: 'cloves',
          },
          metric: {
            amount: 2.0,
            unitShort: 'cloves',
            unitLong: 'cloves',
          },
        },
      },
      {
        id: 11052,
        aisle: 'Produce',
        image: 'green-beans-or-string-beans.jpg',
        consistency: 'solid',
        name: 'green beans',
        nameClean: 'green beans',
        original: '3 handfuls of green beans, chopped',
        originalString: '3 handfuls of green beans, chopped',
        originalName: 'green beans, chopped',
        amount: 3.0,
        unit: 'handfuls',
        meta: ['chopped'],
        metaInformation: ['chopped'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'handfuls',
            unitLong: 'handfuls',
          },
          metric: {
            amount: 3.0,
            unitShort: 'handfuls',
            unitLong: 'handfuls',
          },
        },
      },
      {
        id: 1002030,
        aisle: 'Spices and Seasonings',
        image: 'pepper.jpg',
        consistency: 'solid',
        name: 'ground pepper',
        nameClean: 'black pepper',
        original: 'fresh ground black pepper',
        originalString: 'fresh ground black pepper',
        originalName: 'fresh ground black pepper',
        amount: 6.0,
        unit: 'servings',
        meta: ['fresh', 'black'],
        metaInformation: ['fresh', 'black'],
        measures: {
          us: {
            amount: 6.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
          metric: {
            amount: 6.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
        },
      },
      {
        id: 1012038,
        aisle: 'Spices and Seasonings',
        image: 'dried-sage.png',
        consistency: 'solid',
        name: 'ground sage',
        nameClean: 'ground sage',
        original: '2 teaspoons ground sage',
        originalString: '2 teaspoons ground sage',
        originalName: 'ground sage',
        amount: 2.0,
        unit: 'teaspoons',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 2.0,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 93627,
        aisle: 'Spices and Seasonings;Condiments',
        image: 'dark-sauce.jpg',
        consistency: 'solid',
        name: 'liquid smoke',
        nameClean: 'liquid smoke',
        original: '1/2 to 1 teaspoon liquid smoke, to taste',
        originalString: '1/2 to 1 teaspoon liquid smoke, to taste',
        originalName: 'liquid smoke, to taste',
        amount: 0.5,
        unit: 'teaspoon',
        meta: ['to taste'],
        metaInformation: ['to taste'],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 4053,
        aisle: 'Oil, Vinegar, Salad Dressing',
        image: 'olive-oil.jpg',
        consistency: 'liquid',
        name: 'olive oil',
        nameClean: 'olive oil',
        original: '2 tablespoons olive oil',
        originalString: '2 tablespoons olive oil',
        originalName: 'olive oil',
        amount: 2.0,
        unit: 'tablespoons',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
          metric: {
            amount: 2.0,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
        },
      },
      {
        id: 11821,
        aisle: 'Produce',
        image: 'red-pepper.jpg',
        consistency: 'solid',
        name: 'red bell pepper',
        nameClean: 'red pepper',
        original: '1 red bell pepper, seeded and chopped',
        originalString: '1 red bell pepper, seeded and chopped',
        originalName: 'red bell pepper, seeded and chopped',
        amount: 1.0,
        unit: '',
        meta: ['red', 'seeded', 'chopped'],
        metaInformation: ['red', 'seeded', 'chopped'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 1.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
      {
        id: 10011282,
        aisle: 'Produce',
        image: 'red-onion.png',
        consistency: 'solid',
        name: 'red onion',
        nameClean: 'red onion',
        original: '1 small white or red onion, diced',
        originalString: '1 small white or red onion, diced',
        originalName: 'white or red onion, diced',
        amount: 1.0,
        unit: 'small',
        meta: ['diced', 'white', 'red'],
        metaInformation: ['diced', 'white', 'red'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'small',
            unitLong: 'small',
          },
          metric: {
            amount: 1.0,
            unitShort: 'small',
            unitLong: 'small',
          },
        },
      },
      {
        id: 1012047,
        aisle: 'Spices and Seasonings',
        image: 'salt.jpg',
        consistency: 'solid',
        name: 'sea salt',
        nameClean: 'coarse sea salt',
        original: '1 1/2 teaspoons sea salt, or to taste',
        originalString: '1 1/2 teaspoons sea salt, or to taste',
        originalName: 'sea salt, or to taste',
        amount: 1.5,
        unit: 'teaspoons',
        meta: ['to taste'],
        metaInformation: ['to taste'],
        measures: {
          us: {
            amount: 1.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 1.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 1016168,
        aisle: 'Condiments',
        image: 'hot-sauce-or-tabasco.png',
        consistency: 'liquid',
        name: 'sriracha',
        nameClean: 'sriracha',
        original: '1 teaspoon sriracha or other hot sauce',
        originalString: '1 teaspoon sriracha or other hot sauce',
        originalName: 'sriracha or other hot sauce',
        amount: 1.0,
        unit: 'teaspoon',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
          metric: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
        },
      },
      {
        id: 11529,
        aisle: 'Produce',
        image: 'tomato.png',
        consistency: 'solid',
        name: 'tomatoes',
        nameClean: 'tomato',
        original: '2 medium tomatoes, diced',
        originalString: '2 medium tomatoes, diced',
        originalName: 'tomatoes, diced',
        amount: 2.0,
        unit: 'medium',
        meta: ['diced'],
        metaInformation: ['diced'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 2.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
      {
        id: 6615,
        aisle: 'Canned and Jarred',
        image: 'chicken-broth.png',
        consistency: 'liquid',
        name: 'vegetable stock',
        nameClean: 'vegetable stock',
        original: '3 cups vegetable stock',
        originalString: '3 cups vegetable stock',
        originalName: 'vegetable stock',
        amount: 3.0,
        unit: 'cups',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 709.764,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
    ],
    id: 782601,
    title: 'Red Kidney Bean Jambalaya',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'http://foodandspice.blogspot.com/2016/05/red-kidney-bean-jambalaya.html',
    image: 'https://spoonacular.com/recipeImages/782601-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Red Kidney Bean Jambalaya might be just the <b>Creole</b> recipe you are searching for. One serving contains <b>538 calories</b>, <b>21g of protein</b>, and <b>8g of fat</b>. For <b>$1.69 per serving</b>, this recipe <b>covers 34%</b> of your daily requirements of vitamins and minerals. This recipe from foodandspice.blogspot.com has 52 fans. A few people really liked this main course. Head to the store and pick up brown rice, vegetable stock, liquid smoke, and a few other things to make it today. To use up the sea salt you could follow this main course with the <a href="https://spoonacular.com/recipes/raspberry-sea-salt-brownies-494161">Raspberry Sea Salt Brownies</a> as a dessert. From preparation to the plate, this recipe takes about <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is spectacular. Try <a href="https://spoonacular.com/recipes/red-kidney-bean-dip-148569">Red Kidney Bean Dip</a>, <a href="https://spoonacular.com/recipes/kidney-bean-dip-119992">Kidney Bean Dip</a>, and <a href="https://spoonacular.com/recipes/red-kidney-bean-curry-80686">Red Kidney Bean Curry</a> for similar recipes.',
    cuisines: ['Cajun', 'Creole'],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan'],
    occasions: [],
    instructions:
      'Rinse the kidney beans and brown rice separately. Cover the kidney beans with water and soak for 8 hours or overnight. In a separate bowl, cover the brown rice with water and soak for 8 hours or overnight.Drain and rinse the kidney beans, then transfer to a medium saucepan and cover with fresh water. Bring to a boil, reduce heat to medium-low, cover, and simmer for 1 hour or until just tender but not falling apart. Drain and set aside.Heat the oil in a large saucepan over medium heat. When hot, add the onion and saut for 5 minutes. Now add the garlic, carrots, celery and green beans, and stir for another 5 minutes. Next add the tomatoes, red pepper, eggplant, sage, thyme, marjoram and celery seed, and continue to stir for another few minutes.Pour in the vegetable stock, liquid smoke, rice and the cooked kidney beans. Bring to a boil, reduce heat to medium low, cover, and cook, stirring occasionally, for 45 minutes or until the rice is tender. Add water as necessary if the stew becomes too dry.Season with sriracha, salt and pepper, and taste for seasoning  add more liquid smoke, sriracha, salt, pepper or herbs as desired.',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'Rinse the kidney beans and brown rice separately. Cover the kidney beans with water and soak for 8 hours or overnight. In a separate bowl, cover the brown rice with water and soak for 8 hours or overnight.',
            ingredients: [
              {
                id: 16033,
                name: 'kidney beans',
                localizedName: 'kidney beans',
                image: 'kidney-beans.jpg',
              },
              {
                id: 20040,
                name: 'brown rice',
                localizedName: 'brown rice',
                image: 'uncooked-brown-rice.png',
              },
              {
                id: 14412,
                name: 'water',
                localizedName: 'water',
                image: 'water.png',
              },
            ],
            equipment: [
              {
                id: 404783,
                name: 'bowl',
                localizedName: 'bowl',
                image: 'bowl.jpg',
              },
            ],
            length: {
              number: 960,
              unit: 'minutes',
            },
          },
          {
            number: 2,
            step: 'Drain and rinse the kidney beans, then transfer to a medium saucepan and cover with fresh water. Bring to a boil, reduce heat to medium-low, cover, and simmer for 1 hour or until just tender but not falling apart.',
            ingredients: [
              {
                id: 16033,
                name: 'kidney beans',
                localizedName: 'kidney beans',
                image: 'kidney-beans.jpg',
              },
              {
                id: 14412,
                name: 'water',
                localizedName: 'water',
                image: 'water.png',
              },
            ],
            equipment: [
              {
                id: 404669,
                name: 'sauce pan',
                localizedName: 'sauce pan',
                image: 'sauce-pan.jpg',
              },
            ],
            length: {
              number: 60,
              unit: 'minutes',
            },
          },
          {
            number: 3,
            step: 'Drain and set aside.',
            ingredients: [],
            equipment: [],
          },
          {
            number: 4,
            step: 'Heat the oil in a large saucepan over medium heat. When hot, add the onion and saut for 5 minutes. Now add the garlic, carrots, celery and green beans, and stir for another 5 minutes. Next add the tomatoes, red pepper, eggplant, sage, thyme, marjoram and celery seed, and continue to stir for another few minutes.',
            ingredients: [
              {
                id: 2007,
                name: 'celery seed',
                localizedName: 'celery seed',
                image: 'celery-seed.jpg',
              },
              {
                id: 11052,
                name: 'green beans',
                localizedName: 'green beans',
                image: 'green-beans-or-string-beans.jpg',
              },
              {
                id: 11821,
                name: 'red pepper',
                localizedName: 'red pepper',
                image: 'red-pepper.jpg',
              },
              {
                id: 11209,
                name: 'eggplant',
                localizedName: 'eggplant',
                image: 'eggplant.png',
              },
              {
                id: 2023,
                name: 'marjoram',
                localizedName: 'marjoram',
                image: 'marjoram.jpg',
              },
              {
                id: 11529,
                name: 'tomato',
                localizedName: 'tomato',
                image: 'tomato.png',
              },
              {
                id: 11124,
                name: 'carrot',
                localizedName: 'carrot',
                image: 'sliced-carrot.png',
              },
              {
                id: 11143,
                name: 'celery',
                localizedName: 'celery',
                image: 'celery.jpg',
              },
              {
                id: 11215,
                name: 'garlic',
                localizedName: 'garlic',
                image: 'garlic.png',
              },
              {
                id: 11282,
                name: 'onion',
                localizedName: 'onion',
                image: 'brown-onion.png',
              },
              {
                id: 2049,
                name: 'thyme',
                localizedName: 'thyme',
                image: 'thyme.jpg',
              },
              {
                id: 99226,
                name: 'sage',
                localizedName: 'sage',
                image: 'fresh-sage.png',
              },
              {
                id: 4582,
                name: 'cooking oil',
                localizedName: 'cooking oil',
                image: 'vegetable-oil.jpg',
              },
            ],
            equipment: [
              {
                id: 404669,
                name: 'sauce pan',
                localizedName: 'sauce pan',
                image: 'sauce-pan.jpg',
              },
            ],
            length: {
              number: 10,
              unit: 'minutes',
            },
          },
          {
            number: 5,
            step: 'Pour in the vegetable stock, liquid smoke, rice and the cooked kidney beans. Bring to a boil, reduce heat to medium low, cover, and cook, stirring occasionally, for 45 minutes or until the rice is tender.',
            ingredients: [
              {
                id: 6615,
                name: 'vegetable stock',
                localizedName: 'vegetable stock',
                image: 'chicken-broth.png',
              },
              {
                id: 16033,
                name: 'kidney beans',
                localizedName: 'kidney beans',
                image: 'kidney-beans.jpg',
              },
              {
                id: 93627,
                name: 'liquid smoke',
                localizedName: 'liquid smoke',
                image: 'dark-sauce.jpg',
              },
              {
                id: 20444,
                name: 'rice',
                localizedName: 'rice',
                image: 'uncooked-white-rice.png',
              },
            ],
            equipment: [],
            length: {
              number: 45,
              unit: 'minutes',
            },
          },
          {
            number: 6,
            step: 'Add water as necessary if the stew becomes too dry.Season with sriracha, salt and pepper, and taste for seasoning  add more liquid smoke, sriracha, salt, pepper or herbs as desired.',
            ingredients: [
              {
                id: 1102047,
                name: 'salt and pepper',
                localizedName: 'salt and pepper',
                image: 'salt-and-pepper.jpg',
              },
              {
                id: 93627,
                name: 'liquid smoke',
                localizedName: 'liquid smoke',
                image: 'dark-sauce.jpg',
              },
              {
                id: 1042027,
                name: 'seasoning',
                localizedName: 'seasoning',
                image: 'seasoning.png',
              },
              {
                id: 1016168,
                name: 'sriracha',
                localizedName: 'sriracha',
                image: 'hot-sauce-or-tabasco.png',
              },
              {
                id: 1002030,
                name: 'pepper',
                localizedName: 'pepper',
                image: 'pepper.jpg',
              },
              {
                id: 1002044,
                name: 'herbs',
                localizedName: 'herbs',
                image: 'mixed-fresh-herbs.jpg',
              },
              {
                id: 14412,
                name: 'water',
                localizedName: 'water',
                image: 'water.png',
              },
              {
                id: 2047,
                name: 'salt',
                localizedName: 'salt',
                image: 'salt.jpg',
              },
              {
                id: 0,
                name: 'stew',
                localizedName: 'stew',
                image: '',
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl: 'https://spoonacular.com/red-kidney-bean-jambalaya-782601',
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 6,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 11,
    spoonacularScore: 80.0,
    healthScore: 31.0,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 227.29,
    extendedIngredients: [
      {
        id: 93668,
        aisle: 'Meat',
        image: 'chicken-or-turkey-sausage.jpg',
        consistency: 'solid',
        name: 'chicken sausage links',
        nameClean: 'chicken sausage',
        original:
          "2 fully cooked chicken sausage Links (about 6 oz) sliced into coins – I used Trader Joe's Sweet Italian Chicken Sausage",
        originalString:
          "2 fully cooked chicken sausage Links (about 6 oz) sliced into coins – I used Trader Joe's Sweet Italian Chicken Sausage",
        originalName:
          "fully cooked chicken sausage Links (about sliced into coins – I used Trader Joe's Sweet Italian Chicken Sausage",
        amount: 6.0,
        unit: 'oz',
        meta: [
          'sweet',
          'italian',
          'fully cooked',
          "sliced into coins - i used trader joe's   chicken sausage",
        ],
        metaInformation: [
          'sweet',
          'italian',
          'fully cooked',
          "sliced into coins - i used trader joe's   chicken sausage",
        ],
        measures: {
          us: {
            amount: 6.0,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 170.097,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 10011693,
        aisle: 'Canned and Jarred',
        image: 'tomatoes-canned.png',
        consistency: 'solid',
        name: 'canned tomatoes',
        nameClean: 'canned tomatoes',
        original: '1 14.5-oz. can fire-roasted diced tomatoes, no salt added',
        originalString: '1 14.5-oz. can fire-roasted diced tomatoes, no salt added',
        originalName: 'fire-roasted diced tomatoes, no salt added',
        amount: 14.5,
        unit: 'oz',
        meta: ['diced', 'no salt added', 'canned'],
        metaInformation: ['diced', 'no salt added', 'canned'],
        measures: {
          us: {
            amount: 14.5,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 411.068,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 11282,
        aisle: 'Produce',
        image: 'brown-onion.png',
        consistency: 'solid',
        name: 'onion',
        nameClean: 'onion',
        original: '3/4 cup onion, chopped',
        originalString: '3/4 cup onion, chopped',
        originalName: 'onion, chopped',
        amount: 0.75,
        unit: 'cup',
        meta: ['chopped'],
        metaInformation: ['chopped'],
        measures: {
          us: {
            amount: 0.75,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 177.441,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 11951,
        aisle: 'Produce',
        image: 'yellow-bell-pepper.jpg',
        consistency: 'solid',
        name: 'yellow bell pepper',
        nameClean: 'yellow pepper',
        original: '1 large green bell pepper, seeded, chopped – I used yellow',
        originalString: '1 large green bell pepper, seeded, chopped – I used yellow',
        originalName: 'green bell pepper, seeded, chopped – I used yellow',
        amount: 1.0,
        unit: 'large',
        meta: ['green', 'yellow', 'seeded', 'chopped'],
        metaInformation: ['green', 'yellow', 'seeded', 'chopped'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
          metric: {
            amount: 1.0,
            unitShort: 'large',
            unitLong: 'large',
          },
        },
      },
      {
        id: 11143,
        aisle: 'Produce',
        image: 'celery.jpg',
        consistency: 'solid',
        name: 'celery',
        nameClean: 'celery',
        original: '1 cup celery, chopped',
        originalString: '1 cup celery, chopped',
        originalName: 'celery, chopped',
        amount: 1.0,
        unit: 'cup',
        meta: ['chopped'],
        metaInformation: ['chopped'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'cup',
            unitLong: 'cup',
          },
          metric: {
            amount: 236.588,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 6970,
        aisle: 'Canned and Jarred',
        image: 'chicken-broth.png',
        consistency: 'liquid',
        name: 'low sodium chicken broth',
        nameClean: 'low sodium chicken broth',
        original: '1 cup low-sodium chicken broth',
        originalString: '1 cup low-sodium chicken broth',
        originalName: 'low-sodium chicken broth',
        amount: 1.0,
        unit: 'cup',
        meta: ['low-sodium'],
        metaInformation: ['low-sodium'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'cup',
            unitLong: 'cup',
          },
          metric: {
            amount: 236.588,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 20040,
        aisle: 'Pasta and Rice',
        image: 'uncooked-brown-rice.png',
        consistency: 'solid',
        name: 'brown rice',
        nameClean: 'brown rice',
        original: '1/2 cup uncooked brown rice',
        originalString: '1/2 cup uncooked brown rice',
        originalName: 'uncooked brown rice',
        amount: 0.5,
        unit: 'cup',
        meta: ['uncooked'],
        metaInformation: ['uncooked'],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 118.294,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 11215,
        aisle: 'Produce',
        image: 'garlic.png',
        consistency: 'solid',
        name: 'garlic',
        nameClean: 'garlic',
        original: '1 tbsp. garlic, minced',
        originalString: '1 tbsp. garlic, minced',
        originalName: 'garlic, minced',
        amount: 1.0,
        unit: 'tbsp',
        meta: ['minced'],
        metaInformation: ['minced'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
          metric: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
        },
      },
      {
        id: 1032028,
        aisle: 'Ethnic Foods;Spices and Seasonings',
        image: 'chili-powder.jpg',
        consistency: 'solid',
        name: 'cajun seasoning',
        nameClean: 'cajun seasoning',
        original: '1 tsp. cajun seasoning',
        originalString: '1 tsp. cajun seasoning',
        originalName: 'cajun seasoning',
        amount: 1.0,
        unit: 'tsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
          metric: {
            amount: 1.0,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
        },
      },
      {
        id: 6168,
        aisle: 'Condiments',
        image: 'hot-sauce-or-tabasco.png',
        consistency: 'liquid',
        name: 'hot sauce',
        nameClean: 'hot sauce',
        original: '1/2 tsp. hot sauce, or more to taste',
        originalString: '1/2 tsp. hot sauce, or more to taste',
        originalName: 'hot sauce, or more to taste',
        amount: 0.5,
        unit: 'tsp',
        meta: ['to taste'],
        metaInformation: ['to taste'],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 2027,
        aisle: 'Produce;Spices and Seasonings',
        image: 'oregano.jpg',
        consistency: 'solid',
        name: 'oregano',
        nameClean: 'oregano',
        original: '1/4 tsp. dried oregano',
        originalString: '1/4 tsp. dried oregano',
        originalName: 'dried oregano',
        amount: 0.25,
        unit: 'tsp',
        meta: ['dried'],
        metaInformation: ['dried'],
        measures: {
          us: {
            amount: 0.25,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.25,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 2042,
        aisle: 'Spices and Seasonings',
        image: 'thyme.jpg',
        consistency: 'solid',
        name: 'dried thyme',
        nameClean: 'dried thyme',
        original: '1/4 tsp. dried thyme',
        originalString: '1/4 tsp. dried thyme',
        originalName: 'dried thyme',
        amount: 0.25,
        unit: 'tsp',
        meta: ['dried'],
        metaInformation: ['dried'],
        measures: {
          us: {
            amount: 0.25,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.25,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 15152,
        aisle: 'Seafood',
        image: 'shrimp.png',
        consistency: 'solid',
        name: 'raw shrimp',
        nameClean: 'jumbo shrimp',
        original: '6 oz. raw shrimp, tails removed, deveined, chopped',
        originalString: '6 oz. raw shrimp, tails removed, deveined, chopped',
        originalName: 'raw shrimp, tails removed, deveined, chopped',
        amount: 6.0,
        unit: 'oz',
        meta: ['raw', 'deveined', 'chopped'],
        metaInformation: ['raw', 'deveined', 'chopped'],
        measures: {
          us: {
            amount: 6.0,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 170.097,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
    ],
    id: 648432,
    title: 'Jambalaya Stew',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.foodista.com/recipe/HG72GN7R/jambalaya-stew',
    image: 'https://spoonacular.com/recipeImages/648432-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Jambalaya Stew might be a good recipe to expand your main course recipe box. This recipe serves 4 and costs $2.27 per serving. Watching your figure? This gluten free and dairy free recipe has <b>289 calories</b>, <b>21g of protein</b>, and <b>8g of fat</b> per serving. From preparation to the plate, this recipe takes roughly <b>roughly 45 minutes</b>. It is brought to you by Foodista. <b>Autumn</b> will be even more special with this recipe. If you have cajun seasoning, canned tomatoes, shrimp, and a few other ingredients on hand, you can make it. This recipe is liked by 11 foodies and cooks. It is an <b>affordable</b> recipe for fans of Cajun food. All things considered, we decided this recipe <b>deserves a spoonacular score of 80%</b>. This score is great. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/jambalaya-stew-34848">Jambalaya Stew</a>, <a href="https://spoonacular.com/recipes/gumbo-laya-gumbo-+-jambalaya-stew-793549">Gumbo-laya” (Gumbo + Jambalaya) Stew</a>, and <a href="https://spoonacular.com/recipes/jambalaya-1079154">Jambalaya</a>.',
    cuisines: ['Cajun', 'Creole'],
    dishTypes: ['lunch', 'soup', 'main course', 'main dish', 'dinner'],
    diets: ['gluten free', 'dairy free'],
    occasions: ['fall', 'winter'],
    instructions:
      'Add all ingredients except shrimp to a large pot on the stove. Mix thoroughly. Bring to a boil.\nReduce heat to medium low. Cover and simmer until vegetables are tender and rice is fluffy, about 35 minutes.\nAdd shrimp and re-cover. Continue to cook until shrimp are tender and cooked through, about 6 minutes.\nIf you like, season to taste with salt, black pepper, and additional hot sauce. Serve and enjoy!!!',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'Add all ingredients except shrimp to a large pot on the stove.',
            ingredients: [
              {
                id: 15152,
                name: 'shrimp',
                localizedName: 'shrimp',
                image: 'shrimp.png',
              },
            ],
            equipment: [
              {
                id: 404794,
                name: 'stove',
                localizedName: 'stove',
                image: 'oven.jpg',
              },
              {
                id: 404752,
                name: 'pot',
                localizedName: 'pot',
                image: 'stock-pot.jpg',
              },
            ],
          },
          {
            number: 2,
            step: 'Mix thoroughly. Bring to a boil.',
            ingredients: [],
            equipment: [],
          },
          {
            number: 3,
            step: 'Reduce heat to medium low. Cover and simmer until vegetables are tender and rice is fluffy, about 35 minutes.',
            ingredients: [
              {
                id: 11583,
                name: 'vegetable',
                localizedName: 'vegetable',
                image: 'mixed-vegetables.png',
              },
              {
                id: 20444,
                name: 'rice',
                localizedName: 'rice',
                image: 'uncooked-white-rice.png',
              },
            ],
            equipment: [],
            length: {
              number: 35,
              unit: 'minutes',
            },
          },
          {
            number: 4,
            step: 'Add shrimp and re-cover. Continue to cook until shrimp are tender and cooked through, about 6 minutes.',
            ingredients: [
              {
                id: 15152,
                name: 'shrimp',
                localizedName: 'shrimp',
                image: 'shrimp.png',
              },
            ],
            equipment: [],
            length: {
              number: 6,
              unit: 'minutes',
            },
          },
          {
            number: 5,
            step: 'If you like, season to taste with salt, black pepper, and additional hot sauce.',
            ingredients: [
              {
                id: 1002030,
                name: 'black pepper',
                localizedName: 'black pepper',
                image: 'pepper.jpg',
              },
              {
                id: 6168,
                name: 'hot sauce',
                localizedName: 'hot sauce',
                image: 'hot-sauce-or-tabasco.png',
              },
              {
                id: 2047,
                name: 'salt',
                localizedName: 'salt',
                image: 'salt.jpg',
              },
            ],
            equipment: [],
          },
          {
            number: 6,
            step: 'Serve and enjoy!!!',
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl: 'https://spoonacular.com/jambalaya-stew-648432',
  },
];
